version: '3'
services:
# サービスは2個 db web
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
      # ローカルデータをコピー。これでデータを毎回いれなくてもいい
    environment:
    # 環境変数
      MYSQL_ROOT_PASSWORD: password
  web:
  # dockerfileを使うよ build: .
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
    # ファイル同期 local src -> docker container app
      - ./src:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - db
